# Site settings
title: John Wilger
email: johnwilger@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The personal website of John Wilger; Dad, Cyclist, Software Developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://johnwilger.com" # the base hostname & protocol for your site
twitter_username: jwilger
github_username:  jwilger

highlighter: pygments
safe: true
lsi: false

# Build settings
markdown: kramdown

paginate: 20

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
