# Site settings
title: John Wilger
email: johnwilger@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The personal website of John Wilger; Dad, Cyclist, Software Developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://johnwilger.com" # the base hostname & protocol for your site
twitter_username: jwilger
github_username:  jwilger

exclude: [Gemfile, Gemfile.lock, README.md, vendor, org, .hyde.el]

kramdown:
 input: GFM
 hard_wrap: false
 parse_block_html: true

plugins:
 - jekyll-coffeescript
 - jekyll-paginate

lsi: false
incremental: false
highlighter: rouge
gist:
 noscript: false

paginate: 20

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
